package steam

import (
	_ "embed"
	"encoding/base64"
	"encoding/json"
	"testing"
)

//go:embed testdata/guard_fixtures.json
var guardFixturesJSON []byte

type guardFixtures struct {
	SharedSecret   string `json:"shared_secret"`
	IdentitySecret string `json:"identity_secret"`
	Timestamp      int64  `json:"timestamp"`
	OneTimeCode    string `json:"one_time_code"`
	ConfKeyConf    string `json:"conf_key_conf"`
	ConfKeyAllow   string `json:"conf_key_allow"`
	DeviceID       string `json:"device_id"`
	SteamID        string `json:"steam_id"`
}

func loadGuardFixtures(t *testing.T) guardFixtures {
	t.Helper()
	var f guardFixtures
	if err := json.Unmarshal(guardFixturesJSON, &f); err != nil {
		t.Fatal(err)
	}
	return f
}

// TestGuardCrossValidatedWithPython asserts byte-exact agreement with the
// upstream steampy guard.py implementation (fixtures generated by executing it).
func TestGuardCrossValidatedWithPython(t *testing.T) {
	f := loadGuardFixtures(t)

	code, err := GenerateOneTimeCode(f.SharedSecret, f.Timestamp)
	if err != nil || code != f.OneTimeCode {
		t.Fatalf("otp: %q %v want %q", code, err, f.OneTimeCode)
	}
	conf, err := GenerateConfirmationKey(f.IdentitySecret, "conf", f.Timestamp)
	if err != nil || conf != f.ConfKeyConf {
		t.Fatalf("conf key: %q %v", conf, err)
	}
	allow, err := GenerateConfirmationKey(f.IdentitySecret, "allow", f.Timestamp)
	if err != nil || allow != f.ConfKeyAllow {
		t.Fatalf("allow key: %q %v", allow, err)
	}
	if dev := GenerateDeviceID(f.SteamID); dev != f.DeviceID {
		t.Fatalf("device id: %q want %q", dev, f.DeviceID)
	}
}

func TestProtoBeginAuthMatchesPythonEncoding(t *testing.T) {
	got := encodeBeginAuth("tester", "ZW5jcnlwdGVk", 1755916800)
	want := mustB64(t, "ClJNb3ppbGxhLzUuMCAoWDExOyBMaW51eCB4ODZfNjQ7IHJ2OjEuOS41LjIwKSBHZWNrby8yODEyLTEyLTEwIDA0OjU2OjI4IEZpcmVmb3gvMy44EgZ0ZXN0ZXIaDFpXNWpjbmx3ZEdWayCA1KTFBigBMAM4AUIJQ29tbXVuaXR5")
	if string(got) != string(want) {
		t.Fatalf("begin auth encoding mismatch:\n got=%x\nwant=%x", got, want)
	}
}

func TestDecodeBeginResponse(t *testing.T) {
	// hand-built: client_id=1(7), request_id=2(b"req"), allowed_confirmations=4{type=3}, steamid=5
	var w pbWriter
	w.u64(1, 7)
	w.bytes(2, []byte("req"))
	var inner pbWriter
	inner.u64(1, 3)
	w.bytes(4, inner.buf)
	w.u64(5, 76561199000000000)

	out, err := decodeBeginResponse(w.buf)
	if err != nil {
		t.Fatal(err)
	}
	if out.ClientID != 7 || out.SteamID != 76561199000000000 ||
		len(out.AllowedConfirmations) != 1 || out.AllowedConfirmations[0] != 3 ||
		string(out.RequestID) != "req" {
		t.Fatalf("decoded: %+v", out)
	}
}

func mustB64(t *testing.T, s string) []byte {
	t.Helper()
	d, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	return d
}
